# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ae546b60680ba9edd5f75062b034fc64db53450baab6c27c8272a58ac8862df7e82da0acffa543ea1131d0c107699395f318a73b7637690c5fc899ce10617e9

test:
  secret_key_base: 5cadc275c0279b8cd5b77dbcf323e21006e46b2432def3c553c14a361594ab4fd3838ca117d8decfb3eb5f2c31efdb50763ff0f82a8327c446ff3769d9027d29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
